### ISSUE TITLE
Users comparison is not correctly effective

### ISSUE THREAD

**Issue by savoierider** [oidc-wp/openid-connect-generic#103]
Hi,

Here is the case : 
My Wordpress' user database have a user called "admin".
My app's user database have a user called "admin" too.
I've checked the "Link Existing Users" box
I've checked the "Identify with User Name" box

I try an authentication : your extension detect that a user "admin" is already existing in the wordpress database. 
It's the first time I try to connect to wordpress with the "admin" user from my app so there is no "openid-connect-generic-last-id-token-claim", "openid-connect-generic-last-token-response", "openid-connect-generic-last-user-claim", "openid-connect-generic-subject-identity".
=> The extension creates a new user called "admin2"and linked it with my "admin" user from my app's user database.

This is not exactly what I expect from this option.
The extension would scan if the user already exist and in the case where the user exist but have not been linked : create the link instead of creating a new user.
Maybe you can add an option to choose between these two modes.

Thank you

**Comment by bdegoy** [comment]
Hi,
I am in the same situation than savoierider. 

I could accept the admin2 user, why not? But the creation fails because my OIDC admin has the same e-mail than the WP admin (not an unusaul case), so WP fails with ERROR: Failed user creation.
 
I would like WP link to existing admin.

Thank you daggerhart for a great job!

**Comment by bdegoy** [comment]
I comment myself my previous post.

If we could link a WP user with the same ID as the provided OIDC login, we could access WP with his privileges. A big security breach!

deggerhat did it the right way. What one's should do :
- connect to WP by Login with OpenID Connect with login 'admin'. WP creates 'admin2'.
- connect to the WP administration by the classic method and assign administrator privileges to 'admin2'.

**Comment by kgbsmurf** [comment]
@bdegoy Thank you so much for explaining this.  I was banging my head against this "2" issue.  Makes complete sense.
