### ISSUE TITLE
Password-protected posts trigger login interface?

### ISSUE THREAD

**Issue by lheazel** [oidc-wp/openid-connect-generic#105]
Good day.

I’m working on a theme for my employer and I’ve run into an odd situation. If I password protect a post, navigate to it, input the password and press enter, I’m sent to the account authorization page on my account management service. It’s exactly as though I had just logged in, and then get navigated to the wp-admin page.

This only happens when I have the plugin set to Auto Login-SSO; it’s perfectly well behaved otherwise.

Any ideas?

**Comment by MelvinHB** [comment]
could fix that bay changing the loginpage manually to https://mydomain/wp-login.php
also works with the plugin: https://wordpress.org/plugins/wps-hide-login/
