### ISSUE TITLE
automatic user creation behavior could be changed ? 

### ISSUE THREAD

**Issue by benochen** [oidc-wp/openid-connect-generic#133]
Hi 

Thanks for this great plugin. I have a question. 

When I'm connected with an account with my identity provider which is not link to an existing wordpress user, a new user is created. 

If I understand correctly it is not possible for now to configure the plugin to not create the user instead. 
The method authentication_request_callback() contains the following line 
`
// if we didn't find an existing user, we'll need to create it
		if ( ! $user ) {
			$user = $this->create_new_user( $subject_identity, $user_claim );
			if ( is_wp_error( $user ) ) {
				$this->error_redirect( $user );
				return;
			}
		}
		else {
			// allow plugins / themes to take action using current claims on existing user (e.g. update role)
			do_action( 'openid-connect-generic-update-user-using-current-claim', $user, $user_claim );
		}
`
Does it make sense to add an option in a plugin to prevent the creation of user and just  finalize the login for user who has be mapped to existing user in the wordpres ? 

If I sumbit a PR adding this option, do you will consider it ?

**Comment by ben57univ** [comment]
I have see [this filter](https://github.com/daggerhart/openid-connect-generic#openid-connect-generic-user-login-test) which could work but I think a settings in the UI could be interesting and more user friendly. I have created a  [pull request ](https://github.com/daggerhart/openid-connect-generic/pull/134)  which reflects that.

**Comment by daggerhart** [comment]
Thanks @ben57univ, I'll take a look at this when I get a moment during the week. I appreciate and welcome all PRs!

**Comment by ben57univ** [comment]
Thanks @daggerhart  . Did you have time to take a look ?

**Comment by daggerhart** [comment]
Apologies for the long delay here. Getting caught back up on issues as I can. I left a question on the PR about changing the logic of the checkbox, otherwise this looks good to me. Thanks!

**Comment by benochen** [comment]
Good morning 

I have submit a [PR](https://github.com/daggerhart/openid-connect-generic/pull/148) to propose a integration of this  but I receive no feedback. I'm sure you are busy but I would appreciate to know if it will be include or if I shall maintain my own version of the plugin to have this feature ? 

Thanks

**Comment by benochen** [comment]
Hi 

Issue opened and PR submitted since several months . Is it possible to have a feedback ( or at least a timeframe in which this will be taking into account) or I will not have any chance to have this implemented in the regular plugin package updatable through wordpress  ? 

Regards

**Comment by daggerhart** [comment]
Hi Benochen,

I'll get this commited today and get an updated release out to wp dot org
