### ISSUE TITLE
Logout Url : User automatically signed in after logout

### ISSUE THREAD

**Issue by yamdud** [oidc-wp/openid-connect-generic#138]
hi everyone, 

Having issues around logout. 
Using [ Identity server 4](http://docs.identityserver.io/en/latest/) as Identity provider.
I have added a custom link on navbar for logout(https://example.com/wp-login.php?action=logout). Not sure if this the correct logout url. 
The login works fine, but logout does not redirect to the endsession endpoint hence the user is never logged out. 

I'm quite inexperienced with WordPress so go easy on me :) 

Thanks,

**Comment by bevinhex** [comment]
in my case I think problem might be the nginx proxy settings, specifically proxy_buffer_size stuff, which causing logout abnormality, thus user logs out on wordpress side , but keycloak still thinks user active.
