### ISSUE TITLE
How to disable the auto creation of users?

### ISSUE THREAD

**Issue by gengengengengen** [oidc-wp/openid-connect-generic#157]
Hi,

Thanks for the great plugin!

In my case, I create many users manually in Wordpress local and I want to use these local user information to verify the login user from SSO.

If a login user from SSO not belong to local user, I want the website block this user, but I still found creations happens when new user login from SSO.

How can I disable the auto creation?

I think my case is same as #133

**Comment by benochen** [comment]
Hi 

There is no way currently to disable this. I have submitted a PR to do that here : https://github.com/daggerhart/openid-connect-generic/pull/148 . If you want to patch the plugin yoursel you can use that. 

It seems it has not been tested by the Daggerhart for now but it works for me.
