### ISSUE TITLE
Mapping of roles from oauth system to WordPress

### ISSUE THREAD

**Issue by mrtndwrd** [oidc-wp/openid-connect-generic#164]
I would like to be able to map my SSO system's roles to user soles, so I can create an admin user on the SSO system that automatically gets admin rights on WP as well. Usually this is possible by mapping some "roles" from the SSO system to "roles" inside the application. 

Is that possible with this plugin? Or would it be easy for me to make a PR to make it possible? I'm not good with WP plugins, but I am willing to try if you can push me in the right direction.

Duplicate of #94 but that issue doensn't get me further (either it was possible and the person found out how, or the person found a workaround)

**Comment by MelvinHB** [comment]
You can do that by custom scopes, that you can set in your OIDC provider. take a look in the Documentation. You can find some filters, you can add to your functions.php

Example:

// (User role by Claim/Scope) -->

		add_action('openid-connect-generic-update-user-using-current-claim', function( $user, $user_claim) {
		// Based on some data in the user_claim, modify the user.
		if ( !empty( $user_claim['entitlement_group'] ) ) {
         if ( $user_claim['entitlement_group'] == 'group.Superadmin' ) {
            $user->set_role( 'administrator' );
        }
		if ( $user_claim['entitlement_group'] == 'group.Uploader' ) {
            $user->set_role( 'contributor' );
        }
		if ( $user_claim['entitlement_group'] == 'group.Site_Admin' ) {
            $user->set_role( 'site_admin' );
        }
		if ( $user_claim['entitlement_group'] == 'group.User' ) {
            $user->set_role( 'subscriber' );
        }
		}
		}, 10, 2);

**Comment by MelvinHB** [comment]
yep, that´s correct. this action will only take effect after the 2nd login, because this action modifies the role of already existing users. But you can change the default user Role in Wordpress (“Settings” –> “General” for “New User Default Role” So that you don´t need this:
else {
		$user->set_role( 'contributor' );
	}

**Comment by ms42Q** [comment]
Thanks for your feedback!

Do you think it would be possible to add this as a feature to the plugin?
Maybe by passing a `role_key` option and a mapping for each role. Something like this:

```
  role_key: roles,
  role_mappings:
    administrator: 'admin'
```

**Comment by mrtndwrd** [comment]
Thanks for the answers, @MelvinHB ! Somebody told me that editing `functions.php` manually is a bad practice. Does this means that the best way to configure openid-connect-generic is by making a second plugin which configures it for our purposes? 

We want to use this in a fully automated context, so we'd like to edit the least amounts of files possible. If we would implement a PR that would allow us to configure a role-binding instead (using this plugin's configuration) instead of adding separate functions, would you be willing to merge that?

**Comment by MelvinHB** [comment]
Hello, I'm just a user of this plugin, not a developer. I would recommend using a childtheme, alternatively you can of course use your own plugin, which would mean more effort.

**Comment by timnolte** [comment]
Role mapping can be accomplished using the current hooks. I have an example that I put together mentioned here: https://github.com/daggerhart/openid-connect-generic/issues/198#issuecomment-678820838

**Comment by timnolte** [comment]
After working through configuring the plugin to user Azure AD, Salesforce, and Keycloak, I can say that it is not a universal thing to map IDP roles to WordPress roles. We will be planning on adding additional support and examples to the Wiki in order to assist with this type of request.

**Comment by lrkwz** [comment]
> After working through configuring the plugin to user Azure AD, Salesforce, and Keycloak, I can say that it is not a universal thing to map IDP roles to WordPress roles. We will be planning on adding additional support and examples to the Wiki in order to assist with this type of request.

I would **love** seeing documentation about role mapping in Keycloak

**Comment by dmcm215** [comment]
Same here that would be amazing!
