### ISSUE TITLE
Put login button in custom code

### ISSUE THREAD

**Issue by rajrsingh** [oidc-wp/openid-connect-generic#166]
I want to put a login button in a function I'm writing, so I can't use the shortcode option. I can't find instructions on how to do this. Is this possible?

**Comment by subrato30** [comment]
hi @rajrsingh how did you put this button on anything other than wp-admin page?

**Comment by timnolte** [comment]
@rajrsingh & @subrato30 it has been some time with no response however, you can still use the shortcode in your custom code. You simply need to use the WordPress [`do_shortcode`](https://developer.wordpress.org/reference/functions/do_shortcode/) method.
