### ISSUE TITLE
Access token not updated in WP user meta

### ISSUE THREAD

**Issue by sahnisani** [oidc-wp/openid-connect-generic#178]
Hi guys,

first please let me say i'm not an experienced WP dev. In my project I log in users to WP via my Keycloak server and retrieve the access_token in my Angular custom elements from the WP user meta `openid-connect-generic-last-token-response` via WP ajax to authorize calls to my system.

This works like a charm, except that the access token in the user meta does not appear to be updated after token refresh. Only when the user logs in, the access_token is updated. Is this the correct way to retrieve the current access_token?

Cheers!

**Comment by DDouteaux** [comment]
Hi,

Not part of the development team, but we append to have the same issue here (access_token given by Keycloak and used by a VueJS app after). The only workaround we found was to update the method `ensure_tokens_still_fresh` in the class `OpenID_Connect_Generic_Client_Wrapper` of the plugin by adding `update_user_meta( $user_id, 'openid-connect-generic-last-token-response', $token_response );` before updating refresh token. Thus the field is updated each time we reach the end of the refresh method.
