### ISSUE TITLE
. and - are cut from the preferred_username

### ISSUE THREAD

**Issue by dband** [oidc-wp/openid-connect-generic#187]
Hi,

is there a reason why the plugin does not allow . and - in the username? They are normalized in 'get_username_from_claim' in openid-connect-generic-client-wrapper. 
As far as I checked my Wordpress user table, WP should not have a problem with those characters.

Cheers
Daniel

**Comment by daggerhart** [comment]
I've merged a PR that resolves this issue in 3.6.0

**Comment by schwukas** [comment]
Correct me if I'm wrong but from what I can see both periods and hyphens are still replaced in the current code. I've checked [the line in question](https://github.com/oidc-wp/openid-connect-generic/blob/dev/includes/openid-connect-generic-client-wrapper.php#L705), my WP installation and the [3.6.0 release tag](https://github.com/oidc-wp/openid-connect-generic/releases/tag/3.6.0) and find that all of those versions still contain that bit.
Given that this repo seems unmaintained for the time being, I don't expect too much to happen but nevertheless it might save someone from some headaches :)

**Comment by timnolte** [comment]
@dband this is not going to be fixed as we are moving to use the WordPress Core [strict user sanitization](https://developer.wordpress.org/reference/functions/sanitize_user/).
