### ISSUE TITLE
Error: Your client is configured to authenticate using CLIENT_SECRET_BASIC

### ISSUE THREAD

**Issue by Olsm** [oidc-wp/openid-connect-generic#188]
When using this plugin for Norwegian Bank ID from Signicat after signing in I get redirected to wp-login with the following error message: "Error: Your client is configured to authenticate using CLIENT_SECRET_BASIC"

How can I solve this issue? You may see the Signicat documentation for openid connect protocol here:
https://developer.signicat.com/documentation/authentication/protocols/openid-connect/using-the-openid-connect-protocol/

**Comment by Olsm** [comment]
The issue was that the default authorization method Signicat had was CLIENT_SECRET_BASIC which is the Authorization header Basic, and this plugin use the method CLIENT_SECRET_POST which is client id and secret in the body of the request.

I contacted Signicat about this and they changed to CLIENT_SECRET_POST and now it works fine.

Maybe you could add an option in the wp admin settings to choose between Authorization type Basic and Post? I believe the request then must have instead of client id and secret in the body of the request, this header:
`$request['headers']['Authorization'] = 'Basic ' . base64_encode( "{$request['body']['client_id']}:{$request['body']['client_secret']}" );`

**Comment by timnolte** [comment]
In #207 the plugin had been changed by an outside source to support `client_secret_basic`(https://github.com/daggerhart/openid-connect-generic/issues/207#issuecomment-680512319) so there is a real need to officially support this configuration. The current plugin hooks don't make it possible to implement this.

**Comment by sep76** [comment]
tried to adapt the changes on 3.6 from #207  on the latest 3.8 but are unable to login via norwegian MinID/IDporten (Digdir goverment portal)
curl timeout on the token request.

**Comment by timnolte** [comment]
Since the original issue was resolved by changing the authentication type in the IDP to one that was supported I'm closing this since there are more details provided in the new issue that has been opened for support CLIENT_SECRET_BASIC. #292
