### ISSUE TITLE
empty_user_login / Failed user creation

### ISSUE THREAD

**Issue by Kiina** [oidc-wp/openid-connect-generic#192]
Whenever I try to login a new user I get the empty_user_login message. I added gitlab as OpenID provider and this is the data returned (with the info removed for privacy):

```
array(9) {
      ["sub"]=>
      string(1) ""
      ["sub_legacy"]=>
      string(64) ""
      ["name"]=>
      string(7) ""
      ["nickname"]=>
      string(6) ""
      ["email"]=>
      string(35) ""
      ["email_verified"]=>
      bool(true)
      ["profile"]=>
      string(42) ""
      ["picture"]=>
      string(84) ""
      ["groups"]=>
      array(2) {
        [0]=>
        string(6) ""
        [1]=>
        string(4) ""
      }
```

This is the full error:
```
object(WP_Error)#9665 (2) {
  ["errors"]=>
  array(1) {
    ["failed-user-creation"]=>
    array(1) {
      [0]=>
      string(21) "Failed user creation."
    }
  }
  ["error_data"]=>
  array(1) {
    ["failed-user-creation"]=>
    object(WP_Error)#9664 (2) {
      ["errors"]=>
      array(1) {
        ["empty_user_login"]=>
        array(1) {
          [0]=>
          string(73) "Cannot create a user with an empty login name."
        }
      }
      ["error_data"]=>
      array(0) {
      }
    }
  }
}
```

And these are my settings:
![image](https://user-images.githubusercontent.com/2419591/83960318-c6f1ad00-a887-11ea-84a4-5de415ee440c.png)

I also tried to uncheck and check `Identify with User Name` or switch the identity key to sub with no luck. Am I missing something? All the settings match the variables on the response of the provider....

**Comment by VincentSC** [comment]
Try `sub` instead of `nickname`. See https://github.com/oidc-wp/openid-connect-generic/issues/109#issuecomment-818683912 for what I have

**Comment by Kiina** [comment]
Ah in the newest version it's working with `name` as a key, think it was just related to the old version and is no longer a valid issue.
