### ISSUE TITLE
Authenticate by email if $subject_identity doesn't match

### ISSUE THREAD

**Issue by GloverLab** [oidc-wp/openid-connect-generic#212]
I have a Wordpress installation in which I have created several users, all within the cam.ac.uk domain. 
Cam.ac.uk has its own authentication system (Raven) which can be used with OpenID Connect/OAuth. 
If I don't have the 'create user' checkbox checked, then when I use Raven (connected to OAuth/OpenID Connect) to log in, it gives the query string error 'login-error=identity-not-map-existing-user&message=User+identity+is+not+link+to+an+existing+WordPress+user#'. This is because the $subject_identity key isn't in the users_meta table yet - but there *does* exist a user with the email address which matches. 

I've tinkered with openid-connect-generic-client-wrapper.php to do a WP_USER_QUERY for users with id=$user_claim['email'], and got that working ok. 

Is this something which would be useful to include in a future release? (ie something like 'If I can't find user by $subject_identity meta, should I try by ID matching to email address instead?') And is there a reason I *shouldn't* be finding users by email address? (I have disabled user registration so the only way a user can have an account on the site is if I make it.)

Any help gratefully received. 

Thanks,

Hamish

PS Confusingly this has been posted with my boss's picture as my thumbnail.

**Comment by timnolte** [comment]
@GloverLab you shouldn't need to edit the plugin code to accomplish what you are attempting. You can simply use the `openid-connect-generic-user-login-test` hook(https://github.com/daggerhart/openid-connect-generic#openid-connect-generic-user-login-test) to write your own logic for validating the user should login. Then you can use the `openid-connect-generic-update-user-using-current-claim` hook(https://github.com/daggerhart/openid-connect-generic#openid-connect-generic-update-user-using-current-claim) to update the user's meta data if needed.

**Comment by GloverLab** [comment]
It looks like `openid-connect-generic-user-login-test` will let me control whether the user _should_ be able to log in or not (and kick out poor Terry), but if I use that hook to test for the presence of a user with the correct email address but who doesn't have the required wp_usermeta key (`openid-connect-generic-subject-identity`) and return TRUE if the user exists in the database, I still get the same problem - they're not allowed to log in. 

I think this is because the test for login within the plugin code is using the `openid-connect-generic-subject-identity`to map request to user. (The `openid-connect-generic-user-login-test` hook controls whether `$valid = $client->§( $user_claim, $id_token_claim );` a few lines above is true or not, but that's nothing to do with mapping request to user.)

I'd add a row to the wp_usermeta table in the `openid-connect-generic-user-login-test` hook if I could, but the value it needs to be is `get_subject_identity( $id_token_claim )` and I can't access that in the `openid-connect-generic-user-login-test` hook - I only get `$user_claim` in there.

**Comment by timnolte** [comment]
@GloverLab I'm going to do some further testing as this seems like it might be related to an issue described in #215 with the Create Users option not being checked.

**Comment by GloverLab** [comment]
Great, thanks. For the avoidance of doubt, I don't want to create users on the fly - I've disabled user registration on the site and don't want people to be able to do that themselves; that's how I can control access.

**Comment by timnolte** [comment]
@GloverLab I haven't forgotten about your issue. I need to check the OpenID Connect standards on the piece concerning the Subject Identity. The goal of the plugin is to attempt to match existing users but the Subject Identity is used after authentication as the main key for association with the IDP for future lookups and for token refresh as the Subject Identity is what the IDP would be looking for when a token refresh is requested. I know that not all IDPs implement all aspects of the OpenID Connect standard.

**Comment by GloverLab** [comment]
OK, thanks! I could very definitely update the existing user to add the $subject_identity key after a successful first-time login, using the `openid-connect-generic-update-user-using-current-claim` hook, but it's the initial login that's the current stumbling block. Thanks!

**Comment by GloverLab** [comment]
Hello - Any progress on this one? I'd love to be able to take advantage of future updates to the plugin, but I can't set it auto-updating at the moment. Thanks!

**Comment by jakeh999** [comment]
I think I'm also having the same issue--I think this should clearly be labeled as a bug. 

When the "Link Existing Users" option is checked, but the "Create user if does not exist" option is unchecked, even if there is in fact a WordPress user with a matching e-mail, the following error message is received when attempting to login:

> User identity is not linked to an existing WordPress user.

I'm using Keycloak 11.0.3 as my IDP, WordPress 5.5.3, PHP 7.4.13

Having both "Link Existing Users" and "Create user if does not exist" options checked works for me and existing users can login, but as I don't want users without an existing local WordPress account to be able to authenticate, I added the following workaround to my functions.php file, and everything works as expected:

`add_filter('openid-connect-generic-user-creation-test', function( $result, $user_claim ) {
    // Make sure WP user already exists before 'creating' new user
    $result = email_exists($user_claim['email']);
    return $result;
}, 10, 2);`

**Comment by GloverLab** [comment]
Do you not then end up with two users with the same username?

**Comment by jakeh999** [comment]
@GloverLab For me no, I just double-checked and haven't found any evidence of any duplicate users or user data in the database with my posted workaround. The OpenID user is able to login as the WordPress user with the same e-mail, and all the WP user meta remains as it was before.

**Comment by GloverLab** [comment]
Ok. I like this workaround better than tinkering with the plugin code :-)

**Comment by TaaviE** [comment]
I just encountered the same issue. In the exact same way, I don't have registration enabled, but the account trying to log in exists in the database. The link is just not made for some reason without registration enabled.

**Comment by GloverLab** [comment]
Have you tried the suggestion from @jakeh999 which starts "I think I'm also having the same issue"? That fixes things for me.

**Comment by TaaviE** [comment]
@GloverLab Haven't gotten to it yet, but in general I'd like to avoid such workarounds.

**Comment by ridwankustanto** [comment]
Hi, I have this issue as well, and I tried @jakeh999 approach and it works. But the problem I'm facing now, when I try to login into the wordpress with unauthorize user, it shows me error like this (which is it should be, right?):
![image](https://user-images.githubusercontent.com/19152005/102851792-483d1580-444f-11eb-96b6-60cc3860d227.png)

and when I tried to try back to login, it keeps showing me the error message, turned out the session for unauthorize user has been made. And I need to remove the session manually to get back to login page.

Anything that I can do to prevent the session to be made? Thanks, everyone.

**Comment by jakeh999** [comment]
Hi @ridwankustanto, yes, your screenshot looks like the behavior that's to be expected! 

Since a successful login on the IDP side of things has already occurred, it's not easily possible to prevent or invalidate this on the WordPress side of things. What you could do is perhaps change the error message via a filter (see the plugin documentation) to inform the user they need to sign out of the IDP if they want to use a different account. Or you could just outright redirect the user your IDP logout URL, but this would of course invalidate the user's session across all of your connected services.
