### ISSUE TITLE
username-transliteration-failed on alpine docker wordpress

### ISSUE THREAD

**Issue by ndebeiss** [oidc-wp/openid-connect-generic#214]
Alpine does not support 'ASCII//TRANSLIT' to-code option :
`iconv: destination charset ASCII//TRANSLIT: Invalid argument`

so the line of code :
`$transliterated_username = iconv( 'UTF-8', 'ASCII//TRANSLIT',  $desired_username );`

does not work and I have the message "Username ... could not be transliterated" when returning to the wordpress login page

It should be great if it could detect the support for that destination charset.

**Comment by Kiina** [comment]
Just fyi if anyone wants to use alpine but encouters this issue:

```
RUN apk add gnu-libiconv --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
```

to your Dockerfile and it should work.

**Comment by 1ubuntuuser** [comment]
I'm having this issue, seemed to pop up out of the blue. The above code didn't help in my case so i switched to the non alpine version of wordpress
