### ISSUE TITLE
openid-connect-authorize Page Not Found

### ISSUE THREAD

**Issue by Luzaan** [oidc-wp/openid-connect-generic#237]
Hi,

Firstly let me thank you for the plugin up to now, it seems that it is the type of authentication I would need.

I have setup the app registration in Azure, and I have installed and configured the plugin on Wordpress.
On Wordpress I have checked the "Alternate Redirect URI" checkbox as in Azure I cannot use the default.

My redirect uri is: https://xxxxxxxxxxx.com/openid-connect-authorize

When I go to the login screen, I click on the "Login with OpenID Connect", then enter my Microsoft email.

But then I get the error: 

"The page can’t be found."

Am I suppose to add a page or how can I resolve this issue?

Thank you in advance for your assistance!

Kind Regards

**Comment by timnolte** [comment]
@Luzaan hmm, I'm assuming you navigated to the Permalinks page and made sure to perform a Save there to update the site Permalinks after changing the OpenID Connect plugin setting? I'm also unsure why you can't use the default redirect URI with Azure as I've setup 30+ sites with Azure AD using the default redirect URI.

**Comment by Luzaan** [comment]
Thank you very much for the reply! 
I can't believe I forgot to save the permalinks! That was that problem. Thank you!

Regarding the Azure matter - if I use https://xxxxxxxxxxx.com/wp-admin/admin-ajax.php?action=openid-connect-authorize
as redirect URI in Azure Portal under App Registration, then Azure gives me the error: 
"Error detail: URL may not contain a query string."

I am now getting the following error:

"ERROR (invalid-user-claim): Invalid user claim."

But I am sure this is something I still have to configure, and will do some troubleshooting.

THANK YOU for the reply and help! Much appreciated!

**Comment by Luzaan** [comment]
Thank you very much I did manage to get this resolved. I do however have an issue I cannot resolve yet with regards to existing user signon, but i will open a new issue should I not make any progress.

Thank you again for your great plugin and help.

**Comment by timnolte** [comment]
> Thank you very much for the reply! 
> I can't believe I forgot to save the permalinks! That was that problem. Thank you!
> 
> Regarding the Azure matter - if I use https://xxxxxxxxxxx.com/wp-admin/admin-ajax.php?action=openid-connect-authorize
> as redirect URI in Azure Portal under App Registration, then Azure gives me the error: 
> "Error detail: URL may not contain a query string."
> 
> I am now getting the following error:
> 
> "ERROR (invalid-user-claim): Invalid user claim."
> 
> But I am sure this is something I still have to configure, and will do some troubleshooting.
> 
> THANK YOU for the reply and help! Much appreciated!
> 

@Luzaan that is very strange since I have many examples of this working. I'm wondering if there is something different with how you created your App versus my setups. What I've seen done, and done myself in my development Azure AD is to create an Enterprise Application, not just an Application Registration. Do you go through creating an Enterprise Application?

**Comment by Luzaan** [comment]
@timnolte no I did a normal Application Registration. I will try the Enterprise Application as well. Thank you.

**Comment by Arnold85** [comment]
I tried to create an Enterprise Application as @timnolte suggested, but it would still not accept a URL with a query string. But I think I found the critical option: When the supported account types is set to include personal accounts it wont accept the query string. If it's set to organizational only, than it will accept the URL.

**Comment by timnolte** [comment]
@Arnold85 so my testing and client work has all been focused on more of an enterprise setup and not say personal Office365 accounts.
