### ISSUE TITLE
How to get User Information from Azure?

### ISSUE THREAD

**Issue by Luzaan** [oidc-wp/openid-connect-generic#242]
Hi, 
Thank you again for the plugin! 

How can I get the Azure AD user information of the user logged in through this plugin?
In this case I am specifically looking for the unique user object ID that is linked to the user in Azure AD.

The reason for this is that I am using this plugin on multiple sites for SSO, however the WordPress User ID is different on each site and I need to be able to have one unique identifier regardless on which site they are working on.
The closest I could see in Azure AD is the Object ID of the specific user.

Beyond this, how do I access the other fields set in Azure AD like Job info or Contact Info?

I hope this makes sense.

Thank you in advance, I really appreciate your plugin and help!

Kind Regards
Luzaan

**Comment by timnolte** [comment]
@Luzaan the data from Azure AD will be in the Access Token, which is accessed in the plugin hooks that use the `user_claim`, such as the `openid-connect-generic-update-user-using-current-claim` [hook](https://github.com/oidc-wp/openid-connect-generic#openid-connect-generic-update-user-using-current-claim). This is also stored in the user's metadata as mentioned here: https://github.com/oidc-wp/openid-connect-generic#user-meta-data

**Comment by Luzaan** [comment]
Thank you very much @timnolte Much appreciated! 

Please excuse my "slowness" here, but how can I reference the access token from a plugin I am writing?

**Comment by Luzaan** [comment]
Quick follow-up Thank you very much! I got much information in the meta key - openid-connect-generic-last-user-claim.

Is the sub permanent? will it never change?

**Comment by timnolte** [comment]
@Luzaan here is the Access Token documentation for Azure AD. https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

It very clearly states that the `sub` is unique for the user per client ID. This means that if you have 2 different WordPress sites, each with their own client ID, the `sub` would be different for the same user logging into each site.

**Comment by Luzaan** [comment]
Thank you very much!
