### ISSUE TITLE
user-creation failed if claims does not contain nickname_key (3.8.0 regression)

### ISSUE THREAD

**Issue by drzraf** [oidc-wp/openid-connect-generic#243]
**Describe the bug**
Before 3.8, `get_nickname_from_claim` would return `null` if `nickname_key` (eg: `preferred_username`) was absent.
`create_new_user` would, in turn, just set `$values_missing` or omit setting `$nickname`.
The user-creation wasn't stopped giving a chance for `get_displayname_from_claim`.

With https://github.com/oidc-wp/openid-connect-generic/commit/78ede5dffbb74c9e6a0c007d15104dd83e79dbab#diff-4d7e36ea02368e60c2a32a11344f55b8143ac3656bc95e68204a6fee3bafcdb6R639, then prototype of the function was changed to return WP_Error, but  `create_new_user` wasn't changed accordingly.
(I suggest you look for other errors of this kind in the release)

**To Reproduce**
1. Go to `wp/wp-admin/` with an inexistant user
2. Click on `Login using openid`
3. See error

**Screenshots**

New user would see the following instead:
![Screenshot from 2020-10-22 13-55-20](https://user-images.githubusercontent.com/1169926/96904997-3f8b8b80-146e-11eb-8d52-56cac24e92ec.png)

**Expected behavior**
The absence of said claim should fail safely to give a chance to next hook.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only this plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.
- [x] I can confirm that only 3.8.0 is affected. 3.7.0 works as expected (ignore the missing key).

**WordPress Environment**
- Website URL: 
- PHP Version: 7.4
- WordPress Version: 5.4.1
- Plugin Version: 3.8.0
- Identity Provider: Google
- Relevant Plugin Settings: 
```
array (
  'login_type' => 'button',
  'client_id' => '****.apps.googleusercontent.com',
  'client_secret' => '****',
  'scope' => 'email profile openid',
  'endpoint_login' => 'https://accounts.google.com/o/oauth2/v2/auth',
  'endpoint_userinfo' => 'https://www.googleapis.com/oauth2/v3/userinfo',
  'endpoint_token' => 'https://www.googleapis.com/oauth2/v4/token',
  'endpoint_end_session' => 'https://accounts.google.com/o/oauth2/revoke',
  'identity_key' => 'preferred_username',
  'no_sslverify' => '0',
  'http_request_timeout' => '5',
  'enforce_privacy' => '0',
  'alternate_redirect_uri' => '0',
  'nickname_key' => 'preferred_username',
  'email_format' => '{email}',
  'displayname_format' => '',
  'identify_with_username' => '0',
  'link_existing_users' => 1,
  'redirect_user_back' => 1,
  'redirect_on_logout' => '1',
  'enable_logging' => '1',
  'log_limit' => '150',
)
```

**Comment by timnolte** [comment]
@drzraf thanks for reporting this, and your analysis. We'll work on a fix.

**Comment by drzraf** [comment]
May I ask for any news regarding resolving this 3.8.0 regression?
