### ISSUE TITLE
Attribute Casing issues

### ISSUE THREAD

**Issue by Glowsome** [oidc-wp/openid-connect-generic#247]
**Describe the bug**
When the option 'Identify with User Name' and 'Link existing users' is checked then casing is absolute, if this does not match then the user is/cannot be linked and authentication fails in wordpress.

**To Reproduce**
1. User in backend IdP is defined as ( me as example) 'MHonkoop'
2. User in wordpress is defined as mhonkoop (lowercase)
3. the attribute 'preferred_username' is when successfully authenticating against the IdP transmitted as 'MHonkoop'
4. Plugin is unable to match defined 'preferred_username' to existing account 'mhonkoop' in wordpress.

5. When enabling 'Create if user does not exist' will error out as the User-creation will stumble over the duplicate name.

**Screenshots**

**Expected behavior**
- The Plugin should match regardless of casing.

**Isolating the problem (mark completed items with an [x]):**
- [x ] changed the local account details in the database to match sent casing from IdP (user_login field)
==> Success

**WordPress Environment**
- Website URL:  
- PHP Version: 7.4.9
- WordPress Version: 5.5.3
- Plugin Version: 3.8.0
- Identity Provider: Microfocus AccessManager v4.5.3 
- Relevant Plugin Settings:  [imgur link](https://i.imgur.com/G33mQaV.png)
- scopes requested : openid email profile
- view of what is received from same scopes via an Apache module : [img.ur](https://imgur.com/a/q6sO2N2)

**Comment by lliming** [comment]
The same is true when using email matching (Identity Key is set to "email").  Email matching shouldn't be case-sensitive, but it appears to be case-sensitive in the code now, as we were able to reproduce the behavior described here by changing the case of the email address in the wordpress username field.
