### ISSUE TITLE
Error Identity not map existing user: User Identity not linked to an existing Wordpress user

### ISSUE THREAD

**Issue by martinmurciego** [oidc-wp/openid-connect-generic#249]
Greetings, we have been using this plugin for about a year. And it started giving us problems about a month ago regardless of whether it is version 3.6.0 or 3.8.0. Wordpress users linked to a keycloak platform who had access no longer have access and others continue to have access in this way through the plugin. And over time it happens that some users but not all start to see this error.

**Comment by martinmurciego** [comment]
Apparently I did not upload the image of the error, but here I show it. It is a strange bug because there are users that worked and stop working. An option that was disabled in the plugin I show in a second screenshot is: Create user if does not exist. This is because that option can cause skipping access permissions or at least seeing wp-admin options that it shouldn't.

![openid error](https://user-images.githubusercontent.com/7759127/101911352-fff43c80-3b9e-11eb-9003-f75ccdcfdcdc.jpeg)
![option disable openid](https://user-images.githubusercontent.com/7759127/101911360-0387c380-3b9f-11eb-8468-4ebec41856a8.png)

**Comment by martinmurciego** [comment]
Apparently I did not upload the image of the error, but here I show it. It is a strange bug because there are users that worked and stop working. An option that was disabled in the plugin: Create user if does not exist. This is because that option can cause skipping access permissions or at least seeing wp-admin options that it shouldn't.
![Uploading openid error.png…]()
![Uploading option disable openid.png…]()

**Comment by GloverLab** [comment]
See also #212

**Comment by alerque** [comment]
Ug, I'm beating my head against a similar issue (using Keycloak). Only difference is I've never had a working setup and am just adding this is, no I can't say there isn't something else wrong. This is the error I'm hitting, but I can't find any way to verify even what identify it thinks it is trying to match.

**Comment by alerque** [comment]
Oh yuck.

So I enabled the "Create if user doesn't exist" box just to debug and logged in. Did it create a new user? Nope, it linked the old one. Now the same user works even if I disable the checkbox again, but other users don't work.

This is a bug, it can't seem to link existing users unless the "create new" feature is also enabled.
