### ISSUE TITLE
users being logged out unexpectedly.

### ISSUE THREAD

**Issue by eriksays** [oidc-wp/openid-connect-generic#252]
Has anyone had issues where a user is logged out unexpectedly?
This is where the user has already authenticated (using azure ad), is using the admin, and suddenly finds themselves logged out.
Thanks

**Comment by timnolte** [comment]
@eriksays so there have been some reports of this, I have it on my list to dig into this today.

**Comment by timnolte** [comment]
This is a duplicate of #238
