### ISSUE TITLE
CI is broken for new pull requests

### ISSUE THREAD

**Issue by ChloeTigre** [oidc-wp/openid-connect-generic#258]
**Describe the bug**
CI doesn't  pass even for trivial pull requests. A non-related error message occurs.

I see nothing in my changes that is breaking in any way and yet the builds don't pass. Maybe some error in the version pinning of `Installing mnsami/composer-custom-directory-installer` (see build log)

**To Reproduce**
1. fork the repo
2. make any change
3. open a pull request
yo @daggerhart and @timnolte 
it seems the travis ci is b0rken. 
**Screenshots**
```
  - Installing mnsami/composer-custom-directory-installer (1.0.3): Cloning f2247c448a from cache
PHP Fatal error:  Class Composer\CustomDirectoryInstaller\LibraryPlugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /home/travis/build/oidc-wp/openid-connect-generic/vendor/mnsami/composer-custom-directory-installer/src/Composer/CustomDirectoryInstaller/LibraryPlugin.php on line 10
Fatal error: Class Composer\CustomDirectoryInstaller\LibraryPlugin contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Plugin\PluginInterface::deactivate, Composer\Plugin\PluginInterface::uninstall) in /home/travis/build/oidc-wp/openid-connect-generic/vendor/mnsami/composer-custom-directory-installer/src/Composer/CustomDirectoryInstaller/LibraryPlugin.php on line 10
The command "composer update --prefer-source --no-interaction --optimize-autoloader" failed and exited with 255 during .
Your build has been stopped.
```

(see https://travis-ci.com/github/oidc-wp/openid-connect-generic/jobs/470812258)

**Expected behavior**
CI should run beyond this error message.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only this plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- Website URL: N/A
- PHP Version: N/A
- WordPress Version: N/A
- Plugin Version: dev
- Identity Provider: N/A
- Relevant Plugin Settings: N/A

**Comment by timnolte** [comment]
Yeah, there is a problem with my composer calls to get the correct version of WordPress installed for each build matrix, also Travis is using the latest 2.x version of Composer which has breaking changes from 1.x. Thanks for opening the issue to remind me to work in the build setup.
