### ISSUE TITLE
End Session Endpoint Not Triggering

### ISSUE THREAD

**Issue by joshbell** [oidc-wp/openid-connect-generic#267]
It appears that the End Session Endpoint isn't being triggered when we log a user out of Wordpress.  When the user logs back in, they are immediately authenticated with the identity provider and are able to log directly back in.  

We are using the latest version of Wordpress and this plugin.

When I navigate to the end session endpoint on my own, it logs me out of the Identity Provider, but not when I use the normal wp_logout() function or when pasting the wp_logout_urL() link.

Is it possible to add the end session endpoint to the logout process?

I believe this could be a duplicate of #138 .

**Comment by joshbell** [comment]
WP Download Manager was adding to the wp_logout filter and overriding this plugin.

**Comment by timnolte** [comment]
> WP Download Manager was adding to the wp_logout filter and overriding this plugin.

@joshbell ah, OK, I was scratching my head when reading the initial report as I've been using this and it was working. Let us know if we need to account for what it was that WP Download Manager was doing. Thanks!
