### ISSUE TITLE
Disable registration

### ISSUE THREAD

**Issue by mizansyed** [oidc-wp/openid-connect-generic#275]
Hi
Is it possible to use the plugin without registering a user in WP Database? Trying to use an OIDC as SSO, essentially a single point of truth for multiple WP sites and 000's of users. Are we able to disable registration?

**Comment by timnolte** [comment]
@mizansyed yes, the plugin allows you to enable/disable creating users if they don't exist. A WordPress user does still need to exist that the SSO user maps to. This plugin doesn't rely on the WordPress native registration. You can additionally leverage the hooks in the plugin to automatically perform mapping of roles or deactivation of accounts to "synchronize" with your IDP.

**Comment by timnolte** [comment]
This isn't a valid issue based on the functionality of the plugin, a WordPress user is required to exist to login to the site.
