### ISSUE TITLE
3-minute State Expiration with Daily Cron to clear expired transients

### ISSUE THREAD

**Issue by itcore-ieeecs** [oidc-wp/openid-connect-generic#276]
Hello,

I have a general question in regard to the 180 second expiration time set for the state transient records, and the once-per-day clearing of those 3-minute records.

We're upgrading our systems from an older version of the OpenID Connect code and are integrating version 3.8.1 into our systems.  I'm seeing that Transient records are used primarily for the state values in the "openid-connect-generic-client" file, and a cron setup in the "openid-connect-generic" file.  

Is there a reason for setting the expiration of those to 3 minutes?  And a clearing of those soon-to-be-expired Transients once per 24 hours?

I ask because we're thinking of clearing them every hour perhaps, or 4 times daily, just to keep our wp_options table clear.

Is the 3-minute period a window of cache that the OpenID Connect code needs?

Thanks in advance for the clarification.

Jon

**Comment by daggerhart** [comment]
Hi Jon,

Those times are somewhat arbitrarily set. The idea behind 3 minutes for the transient state is to give the user enough time to login into the other system. I picked 3 minutes as "enough time to find your password" for the IDP service. I use lastpass w/ two-factor on everything, and every 30 days i have to re-login with lastpass (which also has two-factor). So sometimes I need to log into a site, but before I do I have to login to lastpass, but before I do I have to open another 2fa app. That's where 3 minutes came from.

The 24 hour cron job was also picked somewhat arbitrarily. I don't see any problem with that job running more frequently.

Hope this helps!

**Comment by itcore-ieeecs** [comment]
Thanks much, @daggerhart.    I figured it was something along those lines.

Have a good one.
