### ISSUE TITLE
"Invalid State" error

### ISSUE THREAD

**Issue by g-at-ieee** [oidc-wp/openid-connect-generic#277]
Hello, we are having a problem with "Invalid State" error.

From some debug statements, we can see that we are generating the correct URL before we leave to the login site.  However, when it comes back, it often comes back with the wrong state.  The state was generated before but it is old.

An example, we send over a state 'xyz'.  And it might come back as 'xyz', it logs me in and it's fine.  Then next time, we send over a state 'efg' but it comes back as 'xyz'.  If we try again, it comes back as 'xyz' again.

Has anyone else experienced this before?  We know that it is cached somewhere but we can't figure out how to reset that cache.

Thank you

**Comment by timnolte** [comment]
What IDP are you using? What caching do you have on your site? Are you caching the login page and/or the WordPress Dashboard?

**Comment by g-at-ieee** [comment]
We are using SSO.  As far as I know, we are not caching the dashboard or the login page on our QA environment.  We use twig and we have twig caching happening in our prod but not on the QA.  There are also permalinks that are cached in the DB and I tried to reset those also before a login.  Thanks.

**Comment by timnolte** [comment]
When I asked which IDP you are using that means Identity Provider. You perform SSO(Single Sign On) using and IDP. Thanks!

**Comment by timnolte** [comment]
@g-at-ieee can you confirm what Identity Provider you are using?

**Comment by g-at-ieee** [comment]
Hi Tim. Thanks for helping, we figured it out through.  It was a Varnish caching that was caching the outgoing url and it was only reseting every 10 minutes or so.  We had to add some exceptions to it.
