### ISSUE TITLE
PHP Notice in openid-connect-generic-login-form.php

### ISSUE THREAD

**Issue by fminov** [oidc-wp/openid-connect-generic#298]
Hello,

In openid-connect-generic-login-form.php, this code :

		// Record the URL of the redirect_to if set to redirect back to origin page.
		if ( $this->settings->redirect_user_back ) {
			$redirect_url = home_url( add_query_arg( $wp->request ) );
		}

generates a Notice of type "Notice: Undefined offset: 1 in .../wp-includes/functions.php on line 1140"
when $wp->request is just a string (in our use case it contains a string with only the permalink of the page)

suggested bugfix : test $wp->request content before applying add_query_arg on it (only if it is not a string).

Thank you

**Comment by timnolte** [comment]
@fminov were you also seeing an error with Too Many Redirects occuring?

**Comment by fminov** [comment]
@timnolte hello, I have no Too Many Redirect issue, the SSO functionality is working fine.
Just this Notice on the page where I used the openid_connect_generic_login_button shortcode.

**Comment by fminov** [comment]
Tested, bug fixed. Thank you !
