### ISSUE TITLE
From 3.8.4, on login I get ERR_TOO_MANY_REDIRECTS and ERROR (invalid_grant)

### ISSUE THREAD

**Issue by slillo** [oidc-wp/openid-connect-generic#299]
**Describe the bug**
From 3.8.4, on login I get **ERR_TOO_MANY_REDIRECTS** and **ERROR (invalid_grant)**. On logs I can only see a warning related to [undefined array key 1 in functions php](https://github.com/oidc-wp/openid-connect-generic/issues/298). Maybe both issues are related.

**Screenshots**
![login_issue](https://user-images.githubusercontent.com/12492340/114517280-7af95c80-9c3e-11eb-9f04-074ce32595b9.gif)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only this plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- Website URL: local development
- PHP Version: 8.0.3
- WordPress Version: 5.7
- Plugin Version: 3.8.4
- Identity Provider: keycloak
- Relevant Plugin Settings: array (
  'login_type' => 'auto',
  'client_id' => 'wordpresstest',
  'client_secret' => '',
  'scope' => 'openid email profile password offline_access credentials',
  'endpoint_login' => 'https://pluto.svi:38443/auth/realms/WordpressTest/protocol/openid-connect/auth',
  'endpoint_userinfo' => 'https://pluto.svi:38443/auth/realms/WordpressTest/protocol/openid-connect/userinfo',
  'endpoint_token' => 'https://pluto.svi:38443/auth/realms/WordpressTest/protocol/openid-connect/token',
  'endpoint_end_session' => 'https://pluto.svi:38443/auth/realms/WordpressTest/protocol/openid-connect/logout',
  'identity_key' => 'preferred_username',
  'no_sslverify' => '1',
  'http_request_timeout' => '5',
  'enforce_privacy' => '0',
  'alternate_redirect_uri' => '0',
  'nickname_key' => 'preferred_username',
  'email_format' => '{email}',
  'displayname_format' => '',
  'identify_with_username' => '0',
  'state_time_limit' => '',
  'token_refresh_enable' => '1',
  'link_existing_users' => '0',
  'create_if_does_not_exist' => '1',
  'redirect_user_back' => '1',
  'redirect_on_logout' => '1',
  'enable_logging' => '0',
  'log_limit' => '1000',
)

**Comment by timnolte** [comment]
@slillo I find it very interesting that you are reporting this sort of too many redirects issue on the latest version as the most recent couple of versions were supposed to fix/address issues with redirects. In fact it was a different site, running on version 3.8.1, that was already reporting the too many redirects error and it appeared to be related to a missing redirect cookie. The most recent version of the plugin has done away with the use of cookies. The fact that you are receiving an invalid grant error briefly tells me that an error is occuring and the error response is not being handled in a such a way as to prevent sending the user back to the IDP, which you are already authenticated with.

So while there does appear to be a need to better handle error reporting and redirecting back to the IDP it looks like you actually have a configuration issue which is why you are receiving the Invalid Grant error.

**Comment by slillo** [comment]
> @slillo I find it very interesting that you are reporting this sort of too many redirects issue on the latest version as the most recent couple of versions were supposed to fix/address issues with redirects. In fact it was a different site, running on version 3.8.1, that was already reporting the too many redirects error and it appeared to be related to a missing redirect cookie. The most recent version of the plugin has done away with the use of cookies. The fact that you are receiving an invalid grant error briefly tells me that an error is occuring and the error response is not being handled in a such a way as to prevent sending the user back to the IDP, which you are already authenticated with.
> 
> So while there does appear to be a need to better handle error reporting and redirecting back to the IDP it looks like you actually have a configuration issue which is why you are receiving the Invalid Grant error.

I downgraded to 3.8.3 and everything works again.

**Comment by timnolte** [comment]
@slillo hmm, that's very odd since in saw on your screen recording that an invalid grant error was being thrown, which generally indicates an IDP configuration issue. Are you also leveraging any of the plugin's hooks or filters?

**Comment by HshMatera** [comment]
Hello,
I updated the plugin to the latest version 3.8.4 but the redirect problem remains.
In the Plugin I set "Redirect Back to Origin Page" and I expect to see the page from where I logged in, but this does not happen.
The redirect url is wrong, the prefix is ​​duplicated, for example: www.mysite.it/mysite/mysite/postname.
Why does this happen?
Thanks to the availability

**Comment by slillo** [comment]
I tried with only OpenID Connect Generic plugin active, standard theme (Twenty Twenty-One) and no customization to any wordpress source file. In order to avoid issues with previous session I tried to:

1. to completely remove cookies, and other storages;
2. to use incognito mode;
3. to use different browsers

**Comment by timnolte** [comment]
> Hello,
> I updated the plugin to the latest version 3.8.4 but the redirect problem remains.
> In the Plugin I set "Redirect Back to Origin Page" and I expect to see the page from where I logged in, but this does not happen.
> The redirect url is wrong, the prefix is ​​duplicated, for example: www.mysite.it/mysite/mysite/postname.
> Why does this happen?
> Thanks to the availability

@HshMatera can you please open up a new issue for your issue. And please fill out all of the information asked for when opening a new issue. Thanks!

**Comment by timnolte** [comment]
This issue may be related to https://github.com/oidc-wp/openid-connect-generic/issues/298

**Comment by slillo** [comment]
With 3.8.5 I don't have any problem.
