### ISSUE TITLE
Error - Redirect Back to Origin Page

### ISSUE THREAD

**Issue by HshMatera** [oidc-wp/openid-connect-generic#300]
Hello,
I updated the plugin to the latest version 3.8.4 but the redirect problem remains.
In the Plugin I set "Redirect Back to Origin Page" and I expect to see the page from where I logged in, but this does not happen.
The redirect url is wrong, the prefix is ​​duplicated, for example: www.mysite.it/mysite/mysite/postname.
Why does this happen?
Thanks to the availability

WordPress Environment
- PHP Version: 7.3
- WordPress Version: 5.7
- Plugin Version: 3.8.4

**Comment by timnolte** [comment]
@HshMatera what IDP are you using? Also can you provide what you have set for your site's "WordPress Address (URL)" &  "Site Address (URL)"? Thanks!

**Comment by HshMatera** [comment]
As Website url: local development and as IDP Keycloak. With the previous version 3.8.2 of the Plugin it did not give this error but it returned, after the correct login, to the homepage and not to the page where the login took place.

**Comment by timnolte** [comment]
@HshMatera are the "WordPress Address (URL)" & "Site Address (URL)" set as the same.

**Comment by HshMatera** [comment]
Yes, they are identical

**Comment by timnolte** [comment]
@HshMatera is your site installed in a subdirectory?

**Comment by timnolte** [comment]
@HshMatera so I just installed a WP test instance into a subdirectory and see the redirect URLs being set this way. I should have this resolved in the next release.

**Comment by HshMatera** [comment]
I try to move the site to the main directory and test the plugin while waiting for a new version. Thank you

**Comment by HshMatera** [comment]
The redirect works perfectly by not using a subdirectory

**Comment by HshMatera** [comment]
The redirect url perfectly by not using a subdirectory
