### ISSUE TITLE
Rename login button

### ISSUE THREAD

**Issue by jejemontagne** [oidc-wp/openid-connect-generic#309]
I would like to rename the login button` Login Button Shortcode [openid_connect_generic_login_button]`. 
I would like to have just "Connection" instead of " Login with OpenID Connect"
Do you know if it is possible ? And if yes, how ?

Best regards

**Comment by timnolte** [comment]
Yes the shortcode supports the 'button_text' attribute. You can also install [this add-on](https://github.com/oidc-wp/oidc-generic-button-text-addon) which I just created the other day to let you set the button text globally using plugin settings.
