### ISSUE TITLE
error=incorrect-user-claim&message=Incorrect+user+claim.

### ISSUE THREAD

**Issue by sabiertas** [oidc-wp/openid-connect-generic#330]
Good morning I have problems with your plugin, I am using wordpress 5.8 and the plugin version is 3.8.5 I get the error message that I have put in the theme, although I have tried all the possible values ​​in the "Identity Key" field, from At the moment I have solved it by modifying the code of the file "openid-connect-generic-client.php" line 517 putting only return; I do not know how this may affect, on the other hand when creating a user I would like the name and surname to be added.

If it is necessary to pay for it, you could make me a budget, Thanks

**Comment by timnolte** [comment]
@sabiertas changing the code that you have means that you are allowing the authentication to proceed without proper validation. The reason it is failing is because the user claim and ID token claim do not have matching `sub` attributes.

What IDP(Identity Provider) are you using?

**Comment by flavietto** [comment]
Hi @timnolte i'm experimenting the same problem. I'm trying to integrate Keycloak with wordpress and after login form it responds with incorrect-user-claim. After swome debugging i found that $user_claim is empty but id_token claim has some values.
Can you help me?

**Comment by Glowsome** [comment]
@flavietto as you have clearly stated in your comment/adition this is resolved.

Would you be so kind as to closing this ?

**Comment by flavietto** [comment]
Hi @Glowsome,
i can't find the option to close this issue, probably it was opened from someone else? Can you suggest me how to close?
