### ISSUE TITLE
Generic Login Url

### ISSUE THREAD

**Issue by Lurkars** [oidc-wp/openid-connect-generic#333]
I miss the possibility to trigger a login from an external side. Usually an OIDC provider can for example list connected application and users can directly jump into application. For now the login button is always a generated request direct to the IDP with correct state etc. So it is not linkable on external services.

I would suggest a generic login URL which just trigger a redirect with all parameters provided to the IDP. For example sth. like /wp-admin/admin-ajax.php?action=openid-connect-login to redirect to the authorize url with all parameters.

**Comment by Glowsome** [comment]
In a Federative world of authentication the IDP is the one authority that handles authentication.

Giving an external application (which is not federated) the power to be an authorative source for authentication means it should act as an IDP and have a trust with the IDP where the WP site is connected to.

When this is not the case your proposal means you would be able to effectively bypassing the concept of a federative login by having a rogue application act as an authorative source.

**Comment by Lurkars** [comment]
> In a Federative world of authentication the IDP is the one authority that handles authentication.
> 
> Giving an external application (which is not federated) the power to be an authorative source for authentication means it should act as an IDP and have a trust with the IDP where the WP site is connected to.
> 
> When this is not the case your proposal means you would be able to effectively bypassing the concept of a federative login by having a rogue application act as an authorative source.

I quite don't understand this comment in the context. What I am requesting is a url to trigger login for the configured provider. Currently state parameters etc are generated on login page and then this link is generated. I would suggest that this can happen as a redirect under a direct link as I proposed above. This is completely usual behavior in many OIDC client applications and does not bypass anything. I request this, because on IDP site you may want to have a dashboard with all connected applications and trigger direct login (as said, this is the case for MOST OIDC client applications!). For now this is not possible, because you have to go to wp-login to create that url first.

**Comment by Lurkars** [comment]
will close this in favor of  #368.
