### ISSUE TITLE
Creating a keycloak account from WordPress

### ISSUE THREAD

**Issue by mmmccain** [oidc-wp/openid-connect-generic#355]
I am currently authenticating a WordPress site against a keycloak server and if a user does not exist, it will create one on the WordPress site. However, I require the opposite functionality. If a user already is present or is created by WordPress, a new keycloak user will be created with the user information. 

Any suggestion on how I might accomplish this task using oidc-wp? 

Thank you, 

Michael

**Comment by timnolte** [comment]
This is not something that this plugin would directly provide. How accounts are created is something that is handled by the IDP, in your case Keycloak. There is currently an open draft and call for review on a new specification to signal to an IDP, by a client, to perform a user registration, however this is new and most likely not supported by any IDP yet.

* First Public Review Period Started - https://openid.net/2021/12/17/first-public-review-period-for-initiating-user-registration-via-openid-connect-started/
* Draft Spec - https://openid.net/specs/openid-connect-prompt-create-1_0-04.html
