### ISSUE TITLE
Using with keycloak server

### ISSUE THREAD

**Issue by mmmccain** [oidc-wp/openid-connect-generic#356]
I have spent some time learning about keycloak and have figured out the basic functionality of the plugin using a keycloak server. However, I am still guessing on many of the settling. Is there any documentation on the best settings for both keycloak and for oidc-wp for them to work together? With come clarification, this is something I could assist in maintaining.

**Comment by timnolte** [comment]
@mmmccain please move this to a Discussion topic instead of an issue. We don't currently have a Keycloak IDP instance available for testing.
