### ISSUE TITLE
ERROR (invalid-state): Invalid state with keycloak

### ISSUE THREAD

**Issue by mmmccain** [oidc-wp/openid-connect-generic#359]
I am using keycloak as the IDP and have it generally functional if a user is logged-in, but receive the following error after a login attempt from [openid_connect_generic_login_button], it then redirects the user to https://www.example.com/wp-login.php?login-error=invalid-state&message=Invalid+state. The user can then  "Login with OpenID Connect" and be authenticated. 

-
Type: invalid-state
Date: 2022-01-04 02:17:29
User: 0
URI : /wp-admin/admin-ajax.php?action=openid-connect-authorize&state=85473bd6eb22ac8ff848f11d8b8fdcff&session_state=4b19189b-dedd-4307-b1d4-9bde14547bf4&code=
object(WP_Error)#9229 (3) {
["errors"]=>
array(1) {
["invalid-state"]=>
array(1) {
[0]=>
string(14) "Invalid state."
}
}
["error_data"]=>
array(1) {
["invalid-state"]=>
array(4) {
["action"]=>
string(24) "openid-connect-authorize"
["state"]=>
string(32) "85473bd6eb22ac8ff848f11d8b8fdcff"
["session_state"]=>
string(36) "4b19189b-dedd-4307-b1d4-9bde14547bf4"
["code"]=>
string(110) "6cb346f5-a7b3-4aaf-b2c4-e318f15ea15b.4b19189b-dedd-4307-b1d4-9bde14547bf4.caad412c-4d08-4af7-8553-f595df2b7352"
}
}
["additional_data":protected]=>
array(0) {
}
}

**Comment by timnolte** [comment]
This is most likely a Keycloak configuration issue. Can you provide a working example site where this is not functioning? If not if you can provide the URL that is being generated for a user to click on when using the `[openid_connect_generic_login_button]` shortcode that might also help to resolve the issue. You can see an example on our Development testing site(https://dev.oidcwp.net/) and this login button should be working. I'll need to do some updates on our various test IDPs as the domain name changed from the original testing. We have successfully tested the plugin with Google, Microsoft Azure AD, Amazon Cognito, and Oracle IDCS. We don't currently have a Keycloak IDP service available to test with.

**Comment by mmmccain** [comment]
http://lavra.okyrios.org/ is the site where oidc-wp is installed.

https://lavra.okyrios.org/wp-login.php?login-error=invalid-state&message=Invalid+state.
is the URL created by the failed login. It then redirects to a wp-login. If
I click on the Login with OpenID Connect again, it will authenticate but
then attempt to log me into wp-admin/

[image: image.png]

I am happy to work with you with my keycloak instance to get it all working
correctly and documented.

Michael

**Comment by mmmccain** [comment]
![image](https://user-images.githubusercontent.com/97072059/148013930-e41907f4-b65a-4a8e-9f5b-046850b04a6c.png)

**Comment by mmmccain** [comment]
This may be helpful. The behavior with the [openid_connect_generic_login_button] shortcode is the "Login with OpenID Connect" on the wp-login.php. The latter does not produce an error in the log, but attempts to place the user after login in wp-admin and displays "no data to display." 

Also, once a user is logged in, they can log out and back in with no error. It is only when the session has either expired or I clear the session, that says there is an (invalid-state). 

Thank you for your assistance...

**Comment by timnolte** [comment]
@mmmccain given my own testing last night with our dev server and the Keycloak Server we setup I'm wondering if the problem is caching. We have Cloudflare in front of our Dev server with caching on, as well as Litespeed caching and noticed that if you use the shortcode anywhere on your frontend you will most likey  have the invalid state issue. The state for a login is generated always on-the-fly and has a short expiration time. You should only be using the shortcode on a page that will never be cached. If you want provide a login but in many places on your site them you should send users to a non-cached login page.

**Comment by mmmccain** [comment]
I suspect you are correct. It actually works fine all day. The next morning is when I receive the error. I use Litespeed also and just added /login/ uri to the exclude. That also explains why when it is redirected to the wp-login page it works. 

I did an RTFM on the docs you posted and adjusted a few things in keycloak. I will waiting until you make your post to the wiki before making more.

**Comment by mmmccain** [comment]
Please share your setting for keycloak. I know I am missing likely one thing. I stood up another site just to test it and produced the same result. It is a setting in keycloak. 

![image](https://user-images.githubusercontent.com/97072059/148476220-22df1663-fa45-4d25-aff8-879254c41304.png)

If I hit login with OpenID Connect, it will proceed and put the user in /wp-admin/

**Comment by timnolte** [comment]
@mmmccain so 2 things. The first thing is that if you are going to login with SSO you should never be entering login information into the WordPress login screen. Our plugin never passes credentials to the IDP.

The second thing is that I feel like, from what I saw on your site, that you might be trying to use the plugin in a way that it wasn't designed for. Are you trying to use our plugin for some sort of membership site functionality with custom login page and members-only frontend area?

**Comment by timnolte** [comment]
Also, one other piece of information about the "state" is that it has a time limit. If you leave the login screen with the button up on screen for too long before you actually click the button to login there is a good chance the state will have expired and you'll have to try you login again.

**Comment by mmmccain** [comment]
I am currently testing it on 3 sites, but I am only asking it to provide SSO. Nothing fancy. I have SSO set up with the same keycloak server for peertube and for jitsi. One of the sites is a member site, but even in that case, it is only requesting login and password from keycloak. 

I do not use the wp-login, but the shortcode and a login screen. When the shortcode button fails, it returns to the wp-login as you see above. If I then hit the button to login, it completes the process and takes me to /wp-admin/

**Comment by mmmccain** [comment]
I am confident it is a simple setting on the server. I have one instance now behaving consistently. It causes the error above after login and then works if I press the OpenIP Connect button again. I am confident with the right keycloak setting this will simply work. Please post them when you can.

**Comment by mmmccain** [comment]
Here are my setting for the plugin, if that helps. I replaced the secret with XXXXXX, but it is the secret from keycloak. 

![image](https://user-images.githubusercontent.com/97072059/148485539-b1247e77-be5f-4549-94cb-548c4a6750d8.png)

**Comment by timnolte** [comment]
@mmmccain FYI, the [Keycloak Configuration Guide](https://github.com/oidc-wp/openid-connect-generic/wiki/Identity-Provider-Configuration:-Keycloak) is published.

**Comment by mmmccain** [comment]
@timnolte I just made all of the changes. I might have over complicated this a little. All is working, but this is often the case. Let me flush all the case and let things time out and try again. Thank you!
