### ISSUE TITLE
Ability to add multiple OIDC identity providers

### ISSUE THREAD

**Issue by jimkleiber** [oidc-wp/openid-connect-generic#415]
**Is your feature request related to a problem? Please describe.**
I want to enable multiple different OIDC options for my site, not just one, as I want to give my users multiple sign-in options.

**Describe the solution you'd like**
The ability for this plugin to allow multiple different OIDC identity providers. I imagine it would only be applicable when the Auto Login - SSO option is not enabled.

**Describe alternatives you've considered**
Maybe this would be possible by me duplicating the plugin and calling it by another name, but I'm not sure if I would run into errors and I would prefer a more streamlined version, even if that were to work.

**Comment by timnolte** [comment]
To speak to your alternative solution. You would have to change a lot of code in the plugin in order to get another copy to even begin to work, and even then I think you'd run into a lot of problems since the plugin code itself is not written in a way to not stomp on "itself".

**Comment by jimkleiber** [comment]
Ah, I appreciate that! The heads up that I'd be spinning my wheels, that is. Thank you for letting me know.

**Comment by nranderson** [comment]
If you want to give multiple options for users, I would consider using Amazon Cognito or Auth0 as a "middle man" and connect them to the plugin. Then connect additional OIDC IDPs to them.

**Comment by timnolte** [comment]
@jimkleiber as @nranderson pointed out I think it would be better to use and IDP, like Amazon Cognito, that supports federated authentication. That is going to greatly simplify the WordPress configuration required.
