### ISSUE TITLE
support composer/installers ^1.0|^2.0

### ISSUE THREAD

**Issue by drzraf** [oidc-wp/openid-connect-generic#417]
**Describe the bug**
Please relax the constraint inside composer.json
2.0 is what Bedrock now requires and the plugin is incompatible without this.

**To Reproduce**
1. Install latest Bedrock
2. `composer require daggerhart/openid-connect-generic`
3. See error
```
    - Root composer.json requires daggerhart/openid-connect-generic 3.9.0 -> satisfiable by daggerhart/openid-connect-generic[3.9.0].
    - daggerhart/openid-connect-generic 3.9.0 requires composer/installers ~1.0 -> found composer/installers[v1.0.0, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.1).
```

**WordPress Environment**
- PHP Version: 7.4
- WordPress Version: 6.0
- Plugin Version: 3.9.0

**Comment by timnolte** [comment]
@drzraf apologies for the delay with this it's been a busy summer here and I haven't had much time to devote to items here. I'll try to address this and get a release out soon.
