### ISSUE TITLE
Grant type unsupported

### ISSUE THREAD

**Issue by quentinHourriez** [oidc-wp/openid-connect-generic#419]
Hello,

Is it possible to change the grant_type? This one doesn't seem to be supported by source forge?

"ERROR (unsupported_grant_type): Unknown Grant Type, client_secret_post"  https://backstage.forgerock.com/knowledge/kb/article/a27814899

Thanks

**Comment by timnolte** [comment]
This is a function of your Identity Provider and not the plugin.
