### ISSUE TITLE
Redirect wp-login.php to hosted login page

### ISSUE THREAD

**Issue by backpackingseries** [oidc-wp/openid-connect-generic#424]
**Redirect WP-Login to Hosted Login Pages**

I currently use Login by Auth0 plugin that, in addition to Auth0’s native Lock form, offers a hosted login experience which redirects all login and signup requests from /wp-login.php to its (hosted) universal login page on Auth0.

I want OpenID Connect Generic Client plugin, similar to Login by Auth0, to allow redirecting users to hosted login forms provided by OAuth Servers / IDP providers and then log me back into WordPress.

PS: I'm primarily keen to see redirects to Hosted Login pages by AWS Cognito.

Kind regards,

**Comment by timnolte** [comment]
@backpackingseries the plugin has 2 modes, which in either case, both always redirect users to the IDP for authentication. What you saw is the default mode which allows both standard WordPress login or SSO login through an IDP. The other mode that you can configure in the plugin settings will remove the ability to login to WordPress directly and will generally automatically redirect a user to the IDP for authentication. However, in the event of authentication errors a user still may hit a WordPress type of login screen that removes the standard WordPress login form and presents only the SSO/IDP login option via the same style of button.

**Comment by timnolte** [comment]
For clarity this plugin, when configured, will always take users to the IDP login screen for SSO(OpenID Connect) authentication. There are just 2 ways this can be configured to work.

**Comment by backpackingseries** [comment]
Thank you @timnolte Works like a charm!

I continue to learn as I keep playing with your helpful plugin.

Kind regards,
