### ISSUE TITLE
Plugin Overrides WordPress Membership Feature

### ISSUE THREAD

**Issue by backpackingseries** [oidc-wp/openid-connect-generic#428]
Hi,

Seeking clarity on plugin behaviour please:

I have a WordPress site with Memberships disabled - the checkbox for "Anyone can register" is not selected. 

![WordPress Membership Checkbox Deselected Screenshot from 2022-08-17 00-48-11](https://user-images.githubusercontent.com/32608044/184965476-c7faa21b-e06c-495b-ba5f-49a49553cfcf.png)

However, in OpenID Connect - Generic Client plugin, I have selected the option "Create user if it does not exist"

![OpenID Connect Plugin Settings for WordPress Screenshot from 2022-08-17 00-51-44](https://user-images.githubusercontent.com/32608044/184965838-c190b67c-1c0e-465f-bf39-8b6cf7c24d58.png)

In this scenario, I was expecting an attempted user registration to succeed on Cognito but fail on WordPress. However, a user registration succeeds on WordPress too. Is this expected behaviour? Or am I missing anything here? 

Thanks

Kind regards,

**Comment by timnolte** [comment]
Those two settings are really very different things. The WordPress setting for allowing people to register is about presenting the built-in WordPress user registration form. If you don't want users to register via your IDP then you would set that up there. There would be no way to create users that sign-up via your IDP in WordPress if that setting was tied to the WordPress setting. Alternatively, even if you didn't allow sign-ups with the IDP, which is the case with most corporate environments, then there would also be no way to automatically provision users.

**Comment by backpackingseries** [comment]
Thank you @timnolte  Appreciate it. 

Kind regards,

**Comment by backpackingseries** [comment]
A somewhat unrelated question, in case you or anyone you know anyone using this plugin has attempted it and if there's a resource I can refer to.

Is it possible to define federated identity with WordPress dot com as an IDP? That way, I can replace the two buttons with one OpenID button (i remove the standard WP login form with username / password on this page) or simply switch to use the Auto Login SSO option in your plugin - and the hosted UI can then show the button for Login with WordPress:

![WordPress Login with WP DOT COM Screenshot from 2022-08-17 18-46-47](https://user-images.githubusercontent.com/32608044/185145149-12cea269-0801-4e39-9d72-1822a304d86f.png)

Thanks much

Kind regards,

**Comment by timnolte** [comment]
@backpackingseries you can't use WordPress.com as and IDP as they provide no ability other than with JetPack to establish an SSO setup between your self-hosted WordPress site and WordPress.com. This has been asked before and WordPress.com is not setup to be an OpenID Connect IDP.

**Comment by backpackingseries** [comment]
Thank you @timnolte Appreciate your support.

Kind regards
