### ISSUE TITLE
Signout URL with Custom Domain

### ISSUE THREAD

**Issue by backpackingseries** [oidc-wp/openid-connect-generic#429]
Hi,

I got the IDP workflows of registration, login, forgot password, and logout working with your plugin when using a default Cognito domain. However, with a custom domain (say, https://auth.domain.com), Logout does not work for me. I have tried various combinations of Signout URLs in Cognito for a custom domain and nothing works at the moment.

When user logs out by clicking the WordPress Logout link, the IDP displays a message like "**An error was encountered with the requested page**". Unfortunately, there's no other information provided to troubleshoot further.

Referring back to the plugin, I can see _https://www.domain.com/openid-connect-authorize_ as the recommended Redirect URL that I use as the Callback URL in Cognito. This works perfectly with a default Cognito domain (say, appname.amazoncognito.com). It also works for login with custom domain but, in this scenario, log out fails. 

Is there a different Redirect URL I should use for a custom domains?

**Edit**: Another observation to add here. If I keep the plugin's "End Session Endpoint URL" field empty (as shown below), the logout workflow works but partially. A user is then redirected back to the default login page of WordPress.

![Screenshot from 2022-08-17 14-59-54](https://user-images.githubusercontent.com/32608044/185085923-d1ca3460-389a-4d83-b107-8d8f799f4b95.png)

Thanks,

**Comment by backpackingseries** [comment]
So if I keep the plugin's "End Session Endpoint URL" field empty and then use a standard WP filter like this, I can redirect the user to the homepage. 

> add_filter( 'logout_redirect', function() {
    return esc_url( home_url() );
} ); 

Wonder whether a plugin-native solution such as a logout button feature can be created please.

Thanks,

**Comment by timnolte** [comment]
If Cognito is where you are getting the error then that is where your investigation needs to occur. On the plugin side you either provide a valid End Session endpoint or you don't. If one isn't provided then yes, it's only going to take users through the WordPress logout process.

If you are using a custom domain name within Cognito then you should still have an OpenID Connect configuration endpoint that should provide you with all of the configuration details. Normally without a custom domain it would be something like this:

https://cognito-idp.us-west-2.amazonaws.com/us-west-2_WaPN6Bb7H/.well-known/openid-configuration

In your case it should be your custom domain followed by most likely `/.well-known/openid-configuration`.

That endpoint is an OpenID Connect standard that lists out all of the configuration items you would use in the plugin.

**Comment by timnolte** [comment]
> So if I keep the plugin's "End Session Endpoint URL" field empty and then use a standard WP filter like this, I can redirect the user to the homepage. 
> 
> > add_filter( 'logout_redirect', function() {
>     return esc_url( home_url() );
> } ); 
> 
> Wonder whether a plugin-native solution such as a logout button feature can be created please.
> 
> Thanks,

There are already a lot of hooks and filters in the plugin as well as an entire custom plugins settings capability which would allow you to add this functionality. For awareness this plugin is designed more to be used by developers as there is a whole host of hooks and filters to customize how the plugin works on your site. It's been intentionally left light on the out-of-the-box settings in order to keep it generic and customizable.

**Comment by timnolte** [comment]
I think there is possibly still some documentation that used to only like in the project README that was moved to a HOWTO and hasn't made it into the Wiki properly yet. Take a look at this: https://github.com/oidc-wp/openid-connect-generic/blob/dev/HOWTO.md

**Comment by backpackingseries** [comment]
Thank you @timnolte 

Looks like I might have figured it out. So the following worked for me:

### Plugin Configuration - OpenID Connect - Generic Client
End Session Endpoint URL: 
`https://<app.custom.com>/logout?client_id=<clientidhere>&logout_uri=<https://www.domain.com/index.php>`

### AWS Cognito Configuration 
Navigate to -> User pools -> User Pool Name -> App client: App Client Name -> Hosted UI -> Edit -> Allowed sign-out URLs
`<https://www.domain.com/index.php>` // specify the same URL here as mentioned in the plugin for logout_uri 

With this configuration, the user logs out cleanly from AWS Cognito as well as WordPress.

Does that sound about right? Any suggestions here please?

References: [AWS Cognito Logout Endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html)

Kind regards,

**Comment by timnolte** [comment]
@backpackingseries I went and loaded up my test configuration for Cognito and saw that what I had configured for the logout endpoint was this:

- https://nds-wp-oidc-testing.auth.us-east-1.amazoncognito.com/logout?response_type=code&client_id=xxxxxxxxxxxx&redirect_uri=https://oidc-wp.ndigitals.com/wp-admin/admin-ajax.php?action=openid-connect-authorize

**Comment by backpackingseries** [comment]
Thanks @timnolte 

If we use the `redirect_uri` string, then, the user should be redirected back to the login page and I guess this is because of the **openid-connect-authorize** string as mentioned in your URL construct above. Can you please confirm that is what you see at your end?

Also, unless I am overlooking something, I just thought the use of `logout_uri` is more straightforward because, in this case, I can get away without specifying the `response_type` parameter.  With `redirect_uri` if I do not specify the `response_type`, the logout errors out for me.

Kind regards,

**Comment by backpackingseries** [comment]
This is what AWS says in their [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/logout-endpoint.html):

> **logout_uri**
Redirect your user to a custom sign-out page with a logout_uri parameter. Set its value to the app client sign-out URL where you want to redirect your user after they sign out. Use logout_uri only with a client_id parameter. For more information, see [Configuring a user pool app client](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-idp-settings.html).

> You can also use the logout_uri parameter to redirect your user to the sign-in page for another app client. Set the sign-in page for the other app client as an Allowed callback URL in your app client. In your request to the /logout endpoint, set the value of the logout_uri parameter to the URL-encoded sign-in page.

> Amazon Cognito requires either a logout_uri or a redirect_uri parameter in your request to the /logout endpoint. A logout_uri parameter redirects your user to another website.

> **redirect_uri**
> Redirect your user to your sign-in page to authenticate with a redirect_uri parameter. Set its value to the app client Allowed callback URL where you want to redirect your user after they sign in again. Add client_id, scope, state, and response_type parameters that you want to pass to your /login endpoint.

> Amazon Cognito requires either a logout_uri or a redirect_uri parameter in your request to the /logout endpoint. When you want to redirect your user to your /login endpoint to reauthenticate and pass tokens to your app, add a redirect_uri parameter.
