### ISSUE TITLE
Token Response Attribute `expires_in` Should be Optional 

### ISSUE THREAD

**Issue by yogeshbeniwal** [oidc-wp/openid-connect-generic#439]
**Describe the bug**
PHP warning message are shown in server error log with PHP 8.1

**Screenshots**
`[error] 41977#41977: *167373 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "expires_in" in /daggerhart-openid-connect-generic/includes/openid-connect-generic-client-wrapper.php on line 700" while reading response header from upstream`

**Comment by timnolte** [comment]
Just noting that the real issue is that the token `expires_in` attribute is defined as an optional attribute.

https://openid.net/specs/openid-connect-basic-1_0.html#TokenOK

> expires_in
>   OPTIONAL. Expiration time of the Access Token in seconds since the response was generated.
