### ISSUE TITLE
Log Cleanup when Log Limit Changed

### ISSUE THREAD

**Issue by chaddblanchard** [oidc-wp/openid-connect-generic#458]
When the log limit is changed the logs aren't cleared the from WordPress dB. 

**WordPress Environment**
- Website URL: Internal
- PHP Version: 7.4
- WordPress Version: 6.1
- Plugin Version: 3.9.1
- Identity Provider: IdentityServer4
- Relevant Plugin Settings:

**Comment by timnolte** [comment]
@chaddblanchard just noting that the way the plugin is setup it doesn't clear logs when the plugin settings are changed but when a log entry is saved. I did however discover that the plugin was incorrectly handling it's logging where it was actually removing all log entries except for the latest log entry after it went over the limit. I have fixed that incorrect behavior however, the logging class isn't available when saving the plugins settings. The logger is available to the settings screen for the purposes of showing the logs so I'm adding code to give the immediate "appearance" that the log limit change has taken affect but it won't truly take place until the next logging entry has been created.
