### ISSUE TITLE
OIDC with Twitch

### ISSUE THREAD

**Issue by Braastos** [oidc-wp/openid-connect-generic#480]
I tried to use this plugin with twitch.tv, but ran into some problems.

i think i configured the plugin correctly
![grafik](https://user-images.githubusercontent.com/30237621/236584008-5471a22b-14ef-412f-834f-47fe10743fc5.png)

But everytime i try to login, i get an invalid-token-response Error.

My guess is that Twitch requires an additional query parameter (claims, string encoded json) to detect OIDC. The same Endpoint is used for normal OAuth2...
[Twitch Docs](https://dev.twitch.tv/docs/authentication/getting-tokens-oidc/#oidc-authorization-code-grant-flow)

If you requiere more Information i would gladly provide this as best i can.

**Comment by timnolte** [comment]
So first thing I notice is that the `openid` scope is not being included this is usually always required. I'll take a look at the documentation and do some analysis in my testing environment.

**Comment by Braastos** [comment]
I was definetly missing the openid scope...

But now i get an incomplete-user-claim. Probably missed more things.
Thanks in advance for your help 😃

**Comment by timnolte** [comment]
@Braastos confirming I have a configuration that is returning the same results. I'm digging in further to determine the issue.

**Comment by timnolte** [comment]
@Braastos so I turned on the logging and the full error response was there with more of the details. The `email` isn't present in the user claims.

```
["message"]=>
string(39) "Unable to find key: email in user_claim"
["hint"]=>
string(65) "Verify OpenID Scope includes a scope with the attributes you need"
```

When I look at the [OIDC configuration endpoint](https://id.twitch.tv/oauth2/.well-known/openid-configuration) it indicates that `email` should be one of the available claims. It appears that the `user:read:email` scope isn't actually ensuring that the email address is included in the claims.

**Comment by timnolte** [comment]
@Braastos so this is sort of a problem with how Twitch has implemented OIDC. Basically, they are ignoring the scope as the means to return the email address in the user claims and requiring the initial authentication request to include an explicit claims request.
- https://discuss.dev.twitch.tv/t/email-not-returning-from-user-profile/42208
- https://discuss.dev.twitch.tv/t/oauth2strategy-doesnt-provide-email-in-user-profile/22698/5
- https://discuss.dev.twitch.tv/t/no-email-or-email-verified-claim-in-id-token/16937/2
Currently the plugin runs off of the intention that the scopes being requested should tell the IDP which claims to include in the responses. Unless Twitch changes their implementation there is currently no way to get this working without a code change.

As the [OpenID Connect specs](https://openid.net/specs/openid-connect-core-1_0.html#Claims) say:
> Pre-defined sets of Claims can be requested using specific scope values or individual Claims can be requested using the claims request parameter.

**Comment by Braastos** [comment]
As i expected, Twitch always uses some open Spec and then changes things so it doesnt work directly with the spec.

I will look into it...

**Comment by Braastos** [comment]
Just out of curiosity. Would i be able to use the Hooks to add this functionality?
Because if i understand it correctly i only need to send the additonal query parameter "claims=" with a string encoded json with the claims i need?

**Comment by Braastos** [comment]
Ok, i got it working with a filter...
