### ISSUE TITLE
Check if the session is active

### ISSUE THREAD

**Issue by diegopatinor** [oidc-wp/openid-connect-generic#502]
Is there a way to check if the section in the IDP is still active? If the user logs out of another application, they continue with the active section in WordPress.

For this, the Check session iframe is usually used.

**Comment by timnolte** [comment]
So is sounds like you are looking for Front Channel Logout, which there is an existing open issue(https://github.com/oidc-wp/openid-connect-generic/issues/336) for it with a potential PR. The other option that has also been brought up is Back-Channel Logout(https://github.com/oidc-wp/openid-connect-generic/issues/205)

Neither of these options are yet implemented officially.

**Comment by diegopatinor** [comment]
thanks!, I will see these references
