### ISSUE TITLE
Possibility to define our own redirect_uri

### ISSUE THREAD

**Issue by dblas** [oidc-wp/openid-connect-generic#527]
Needed in many cases where we do not want to modify the reverse proxy settings (in order to "forget" the /openid-connect-authorize path which leads to errors in WP).
A simply https://www.mywordpress.org is generally enough for a redirect_uri.
Thx,
db

**Comment by DamChtlv** [comment]
Hi @dblas 
Have you tried changing the `redirect_uri` using **[admin_url](https://developer.wordpress.org/reference/hooks/admin_url/)** _(if standard redirect_uri : `admin-ajax.php?action=openid-connect-authorize`)_ / **[site_url](https://developer.wordpress.org/reference/hooks/site_url/)** _(if alternate redirect uri : `/openid-connect-authorize`)_ filter hooks?

**Comment by timnolte** [comment]
@dblas hooking into the root of the site will cause the plugin to have to check all visitor requests to the main site homepage, this will cause performance impacts on your site when there is no site login happening. The aspecting of incorrectly configuring your IDP with the correct Redirect URI is not really a fix and will generally just cause way more problems. It would only be in the case of when the plugin is configured to put entire site is behind SSO that this would even start to be a valid case for changing the Redirect URL as such.
