### ISSUE TITLE
WordPress Logout Error with Passage.id

### ISSUE THREAD

**Issue by gojo-limitless** [oidc-wp/openid-connect-generic#537]
I was able to successfully implement **Passage.id** with your plugin on my website.

I had to remove the userinfo endpoint URL to get it working, as I encountered this issue initially: [https://github.com/oidc-wp/openid-connect-generic/issues/152](https://github.com/oidc-wp/openid-connect-generic/issues/152)

That fixed and made the login page work. However, whenever I try to logout, by clicking on `https://website.com/wp-login.php?action=logout&_wpnonce=value`

I get the following error, and the session does not logout: [https://prnt.sc/-2-M8YCYRvrm](https://prnt.sc/-2-M8YCYRvrm).. 

And, my endpoint URI is as instructed in Passage's documentation: https://docs.passage.id/helpful-guides/ecommerce-guides/wordpress-and-woocommerce#configure-the-oidc-client-to-use-passage, which looks like: `https://name.withpassage.com/logout`

Any assistance is appreciated, thanks in advance!

**Comment by timnolte** [comment]
I think your "Allowed logout URL" is configured wrong in Passage.

**Comment by gojo-limitless** [comment]
> I think your "Allowed logout URL" is configured wrong in Passage.

I tried setting the allowed logout URL to

https://name.com/wp-login.php?action=logout

I'm not sure what else should I add?

They don't have any detailed documentation regarding what to add there. Just the one I linked.

I've also mailed them, but I haven't gotten any response. I've tried their Discord channel next. If I find a solution, I'll update that here soon.

**Comment by gojo-limitless** [comment]
Thanks to Passage's Discord support, a community member just pointed out a potential mismatch in the "Allowed logout URL", where I had an extra trailing /, I removed it, and that worked.

So, @timnolte you were correct, I just realized the trailing slash when someone pointed it out. Now, logout works!
