### ISSUE TITLE
Ending users session from Keycloak webui doesn't log user out from client (wordpress)

### ISSUE THREAD

**Issue by joshdinsdale** [oidc-wp/openid-connect-generic#543]
I have Openid-connect-generic connecting to keycloak as per the instructions in the Wiki.

User can login to wordpress via keycloak, session starts, they are logged in. If they initiate a logout from Wordpress, they are logged out and their session shows as logged out in the keycloak admin UI.

However if i trigger a logout of the user from the keycloak admin ui, the user does not get logged out of wordpress.

Is this expected behaviour or do i have something configured incorectly?

Keycloak version 24, latest Openid-connect-generic plugin version.

**Comment by timnolte** [comment]
The plugin doesn't currently support Back Channel Logout. This is something that is on the list of items we'd like to support. We are looking at shifting to a dedicated OIDC library for much of the underlying protocol handling and we're hoping that the chosen library may allow us to implement this feature quickly.

You can read a thread of details here: https://github.com/oidc-wp/openid-connect-generic/issues/205
