### ISSUE TITLE
Invalid-State Error

### ISSUE THREAD

**Issue by jonyking** [oidc-wp/openid-connect-generic#548]
Hello,

we use your plugin in connection with Keycloak. We decided since 2 Weeks problems with the login. We can not login cause we got the wordpress error "invalid-state" or "access token expired". 
This seems a problem with your plugin.

**Comment by timnolte** [comment]
Have you updated the plugin? Did you try rolling back if you did? What version of the plugin, WordPress, Keycloak are you using?

**Comment by jonyking** [comment]
We are using the following Versions:
1. WordPress 6.5.4 (rolled back to 6.5.x, same error)
2. Plugin: 3.10.0 (rolled back to 3.9.0, same error)
3. Keycloak 20.0.3 (No Updates done)

We have nothing changed in our environment. Caching is disabled on our server.

**Comment by jonyking** [comment]
What we have done so far:

1. Server Restart
2. Deactivated all other Plugins, same result
3. Restarted Keycloak
4. Looked in Error-Logs, nothing to see

**Comment by jonyking** [comment]
@timnolte I had one idea cause of an change of an external service provider. They had made an issue .... I am sorry for that.

They copied one time the url for an button but don't use the shortcodes for it. So the nonce is everytime the same for every user and that is not working this way. We can close this comment!
