### ISSUE TITLE
After signing it, session will always expire after a period of time regardless if i am active or not

### ISSUE THREAD

**Issue by Popcorncandy09** [oidc-wp/openid-connect-generic#549]
**Describe the bug**
After signing in via Authentik, i can access the admin panel and start edits, but after some time it will pop-up with a session expired pop-up box and ask me to sign in again...there doesn't seem to be any easy way to extend this in the settings and it causes me to lose work when editing in Elamentor. 

**To Reproduce**
Login with OIDC
Period of time i will see the pop-up

**Screenshots**
![image](https://github.com/oidc-wp/openid-connect-generic/assets/41139623/5387d521-bc78-4bfe-b995-d3d3a6863ac3)

**Expected behavior**
To stay logged in more than 3 minutes.

**Comment by timnolte** [comment]
Please see the comments, and a temporary fix, in the support forums. There is already a known issue that will be fixed in the next release. 

https://wordpress.org/support/topic/session-expired-prematurely/

**Comment by Popcorncandy09** [comment]
Closing it before confirming i know how to implement said fix isn't very helpful

**Comment by Popcorncandy09** [comment]
Can you explain how to implement said fix...as when i tried to do this it still didn't work for me.

**Comment by timnolte** [comment]
As the support forum indicated there is a hook you can use. The other person said it worked for them. What is it you need to know?

https://wordpress.org/support/topic/session-expired-prematurely/#post-17811498

**Comment by timnolte** [comment]
I'm now out of town and will have limited connectivity until next week. You should be able to use that filter and set how long you want your session to be good for in number of seconds.

**Comment by Popcorncandy09** [comment]
Where do you add this hook? i have tried adding it as a custom plugin...doesn't work, added it into code snippets, also didn't work. I am not familiar with hooks

**Comment by timnolte** [comment]
@Popcorncandy09 that filter is a Core WordPress filter that you can use, documented here.

https://developer.wordpress.org/reference/hooks/auth_cookie_expiration/

There is an example you can use noted here:

https://developer.wordpress.org/reference/hooks/auth_cookie_expiration/#comment-1773

**Comment by timnolte** [comment]
@Popcorncandy09 you can also put code in a Must Use(MU) plugin.

https://developer.wordpress.org/advanced-administration/plugins/mu-plugins/

**Comment by Popcorncandy09** [comment]
Unfortunately doesn't seem to have made a difference :/ 
![image](https://github.com/oidc-wp/openid-connect-generic/assets/41139623/a1aa1b4c-fdc9-4c64-9e08-ff5eb1c59fb4)

**Comment by timnolte** [comment]
@Popcorncandy09 I don't know what to tell you it works for others. There will be a change coming out soon that will be removing any plugin specific session length changes from what is in place by default for WordPress. There was a long standing incorrect mapping of token expiration to WordPress session expiration that has been in place. I think this was a misunderstanding of what the token expiration was to be used for. There is also a `remember_me` hook that you can also try setting.

```php
add_filter( 'remember_me', '__return_true' );
```

**Comment by Popcorncandy09** [comment]
Thanks, I'm struggling to get anything to work, do you have an ETA on the fix?

**Comment by timnolte** [comment]
No there is no ETA. The methods outlined to use the hooks the control session expiration should be enough for the time being. My capacity is limited right now and I am only able to devote time for critical items. There is something more going on with your setup if your sessions are instantly expiring.

**Comment by JakeyPrime** [comment]
With programming knowledge but limited programming knowledge with PHP, it seems this issue is entirely related to Authentik given the reports coming in all being Authentik installs, including mine.

However, this is default settings, even with higher session times it seems to be only an issue with Wordpress and this plugin, and fine with other oauth2 apps using Authentik. It's dissapointing considering this is Authentik's recommended plugin on their own documentation

I wouldn't say the sessions expire instantly, but the expiry time seems to be roughly 2-3 minutes. 

Happy to help debug if needed.

**Comment by Popcorncandy09** [comment]
I'm still experiencing this issue.

**Comment by JakeyPrime** [comment]
> I'm still experiencing this issue.

@timnolte mentioned on the Wordpress support forums that he would have a fixed pushed out in a few weeks a couple weeks ago, probably has to spin up an authentik install to test it out, give it time, I'm sure he will get it updated eventually.

Although, it would be nice to see the issue reopened to validate our concerns and issues.

**Comment by Popcorncandy09** [comment]
> > I'm still experiencing this issue.
> 
> @timnolte mentioned on the Wordpress support forums that he would have a fixed pushed out in a few weeks a couple weeks ago, probably has to spin up an authentik install to test it out, give it time, I'm sure he will get it updated eventually.
> 
> Although, it would be nice to see the issue reopened to validate our concerns and issues.

He's now banned from updating his plugins, can you help debug/fix?

**Comment by timnolte** [comment]
FYI, just a note that the session timeout bug was fixed and is currently available in the `develop` branch. Right now I am preparing for a transition with @daggerhart concerning the on-going maintenance of the plugin. A fork of this plugin that will be seen as a sort of forked "upstream" is being worked on as well. I'll be working with @daggerhart to make that fix available more broadly here as well.

**Comment by timnolte** [comment]
FYI, please continue to watch the pinned issue for updates. https://github.com/oidc-wp/openid-connect-generic/issues/568
