### ISSUE TITLE
Updating Keycloak user information based on WordPress changes

### ISSUE THREAD

**Issue by MegaKeon** [oidc-wp/openid-connect-generic#557]
When changing e-mail, phone number, role or any aspect of a user in WordPress, the changes are not reflected on Keycloak. Most of the changes done to users, like role and e-mail changes, are done by WordPress and there should be an option to reflect those changes on there, or an easier way to make it so shown in the documentation.

**Comment by timnolte** [comment]
This plugin doesn't do any sort of writes back to the IDP, that is generally not how it works with single-sign-on and authentication. This plugin is only an OpenID Connect client.
