### ISSUE TITLE
Anyway to configure on the command line?

### ISSUE THREAD

**Issue by dac11011** [oidc-wp/openid-connect-generic#562]
Hi,

Is there anyway to configure this plugins settings on the command line some where? Or in a database?
I'd like to do this without having to use the web gui settings page.

Thank you!

**Comment by timnolte** [comment]
So you can configure a large majority of the settings via configuration constants in the `wp-config.php` file.

You can find a list here: https://github.com/oidc-wp/openid-connect-generic/wiki/Configuration-Environment-Variables-Constants
