### ISSUE TITLE
Customize Login Button

### ISSUE THREAD

**Issue by Phoenix-Ignited-Tech** [oidc-wp/openid-connect-generic#565]
It would be nice to add support for customizing the "Login with OpenID Connect" button. All I need is to change the button text, no css etc. (Users/Customers might not know what "Login with OpenID Connect" means) If no one is adverse to this prospect I'll submit a pull-request.

**Comment by timnolte** [comment]
This is already possible. There is a hook that does this.

**Comment by timnolte** [comment]
https://github.com/oidc-wp/openid-connect-generic/wiki/Hooks---Actions-&-Filters#openid-connect-generic-login-button-text

**Comment by Phoenix-Ignited-Tech** [comment]
Great! Thanks!
