### ISSUE TITLE
Logout redirection URI redirects to login page 

### ISSUE THREAD

**Issue by chbossard** [oidc-wp/openid-connect-generic#566]
Hi

I love this plug-in. I have a slight issue. I use a WordPress site and Keaycloak as an IDP. Login works fine. After the login, the user is redirected to the page he logged in from. But when the user uses the WordPress logout button, he is redirected to the Keycloak login page instead of the website's main page or the page he logged out from. 

Can we configure this behaviour?

**Comment by timnolte** [comment]
Do you not want the user to be logged out of Keycloak? If you only want them logged out of WordPress then just don't configure the logout endpoint in the plugin settings screen. Then they will just logout as normal.

**Comment by chbossard** [comment]
If I leave the logout endpoint field empty. The useres can not logout at all.

**Comment by chbossard** [comment]
I found the issue. I also use the SolidSecurity plugin on the website. When the option to "hide backend" in advanced settings is enabled, the redirects do not work. Well, it always takes you back to the login page. When I deactivate this setting and leave it in the default configuration, it works as expected.
