### ISSUE TITLE
Encode Redirect URL in State to Prevent Issues with Missing Cookies

### ISSUE THREAD

**Issue by pjeby** [oidc-wp/openid-connect-generic#57]
If an error occurs during the login process (e.g. too long to login, missing state, etc.), `handle_redirect_cookie()` resets the redirect cookie while on the login page that displays the error message.  It should not change the URL if the cookie is set and there is no `redirect_to` in the URL.

On a related note, why does the redirect cookie have an expiration time instead of being a session cookie?  There is no reason I can think of for it to hang around for 24 hours even if the browser is closed, nor for it to expire after 24 hours if the session is still active.  ISTM that it should be a session-duration cookie.

Alternately, the cookie could be done away with altogether, by encoding it as part of the `state` field in the authorization URL.  When the callback happens, the state field could be split back out into the state and the redirect URI.  All the cookie-specific code would go away, and the redirect URI calculation/cookie setting wouldn't have to be done on every request any more; the redirect URI would be determined on-demand.

**Comment by timnolte** [comment]
@daggerhart we should consider changing how the redirect URL is managed and follow the example by some other code(looks like sort of a fork) mentioned here: https://github.com/oidc-wp/openid-connect-generic/pull/59#issuecomment-417364549

As I've read into more about the OIDC protocol it is very common, and seems like best practice, to encode things like the redirect URL into the state which can then later be decoded without fear of losing the cookie. There are currently 2-3 new issues that have been opened recently that point to cookie issues with the redirects.

**Comment by timnolte** [comment]
@pjeby a new version of the plugin has been released that should have this implemented. I did opt to store the redirect URL along with the state via the existing state transient instead of attempting to encode/decode the redirect URL into the state in order to protect against possible state collisions and decoding issues.

**Comment by pjeby** [comment]
No worries, as I mentioned on #59 (the PR I submitted to fix this), I wrote a replacement for this plugin and moved on about three years ago.  Thanks for the heads-up though.
