### ISSUE TITLE
sample configurations

### ISSUE THREAD

**Issue by drzraf** [oidc-wp/openid-connect-generic#71]
It's supposed that Google is a supported openid provider.
It already provides a metadata URL which should ease configuration:
 https://accounts.google.com/.well-known/openid-configuration
Anyway the **"End Session Endpoint URL" is not clear**. Is it actually what Google calls a "revocation_endpoint"?

Samples of configuration for common providers would be welcome or, better, make use of the metadata URL to automatically fill the fields.

**Comment by daggerhart** [comment]
Making use of the metadata URLs sounds awesome. I definitely want to look into that.

In this case, yes the End Session Endpoint URL is meant to be that URL where the access token is revoked. But, it is very simple and expects the url will automatically handle the revocation upon being visited (GET request).

I've not tested this with Google, do they expect a POST request or something more than simply hitting a URL?

**Comment by drzraf** [comment]
For the record:
https://gitlab.com/.well-known/openid-configuration
https://auth0.auth0.com/.well-known/openid-configuration
https://accounts.google.com/.well-known/openid-configuration
https://login.yahoo.com/.well-known/openid-configuration
https://connect-op.herokuapp.com/.well-known/openid-configuration
https://login.salesforce.com/.well-known/openid-configuration
https://login.windows.net/common/.well-known/openid-configuration
https://www.paypalobjects.com/.well-known/openid-configuration


See also:
https://connect2id.com/products/nimbus-oauth-openid-connect-sdk/openid-connect-providers

**Comment by mbrowne** [comment]
To answer the question about "End Session Endpoint URL", I used this endpoint and it seems to work fine (although I don't actually know if it's doing anything on Google's end):

https://oauth2.googleapis.com/revoke

It's listed at https://accounts.google.com/.well-known/openid-configuration as the "revocation_endpoint".

**Comment by timnolte** [comment]
Noting that the Wiki has been compiling IDP setup guides. Additionally, one of the nect major releases is going to include using the OIDC configuration discovery endpoint to pre-configure the plugin settings.
